// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc190.2014RobotProject.subsystems;
import org.usfirst.frc190.2014RobotProject.RobotMap;
import org.usfirst.frc190.2014RobotProject.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class Shooter extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    DigitalInput limitSwitch2 = RobotMap.shooterLimitSwitch2;
    DigitalInput limitSwitch1 = RobotMap.shooterLimitSwitch1;
    DoubleSolenoid doubleSolenoid1 = RobotMap.shooterDoubleSolenoid1;
    DoubleSolenoid doubleSolenoid2 = RobotMap.shooterDoubleSolenoid2;
    DoubleSolenoid doubleSolenoid3 = RobotMap.shooterDoubleSolenoid3;
    DigitalInput digitalInput1 = RobotMap.shooterDigitalInput1;
    DigitalInput digitalInput2 = RobotMap.shooterDigitalInput2;
    DigitalInput digitalInput3 = RobotMap.shooterDigitalInput3;
    DigitalInput digitalInput4 = RobotMap.shooterDigitalInput4;
    AnalogChannel potentiometer1 = RobotMap.shooterPotentiometer1;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}
