//This is the Collector Subgroup
//It has one motor for the rollers, a limit switch for ball detection,
//a piston for opening and closing the claw, and a reed switch to check 
//if the piston is open.
package org.usfirst.frc190.CurrentRobotProject.subsystems;
import org.usfirst.frc190.CurrentRobotProject.RobotMap;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
public class Collector extends Subsystem {
    //There is no servo on the collector, only the piston`
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController rollerMotor = RobotMap.collectorRollerMotor;
    DigitalInput ballDetector = RobotMap.collectorBallDetector;
    Solenoid clawPiston = RobotMap.collectorClawPiston;
    DigitalInput clawOpenDetector = RobotMap.collectorClawOpenDetector;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public boolean isCollected() {
        return !ballDetector.get();
    }
    public void setRollerSpeed(double speed) {
        rollerMotor.set(-speed);
    }
    public void stop() {
        rollerMotor.set(0);
    }
    public boolean isClawOpen() {
        return clawOpenDetector.get();
    }
    public void openClaw() {
        clawPiston.set(true);
    }
    public void closeClaw() {
        clawPiston.set(false);
    }
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    }
}
