// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc190.2014RobotProject;
    
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController drivetrainSpeedController1;
    public static SpeedController drivetrainSpeedController2;
    public static RobotDrive drivetrainRobotDrive2Motors;
    public static SpeedController drivetrainSpeedController3;
    public static SpeedController drivetrainSpeedController4;
    public static SpeedController drivetrainSpeedController5;
    public static SpeedController drivetrainSpeedController6;
    public static RobotDrive drivetrainRobotDrive4Motors;
    public static Encoder drivetrainQuadratureEncoder1;
    public static Encoder drivetrainQuadratureEncoder2;
    public static Ultrasonic drivetrainUltrasonic1;
    public static SpeedController collectorSpeedController1;
    public static DigitalInput collectorLimitSwitch1;
    public static Servo collectorServo1;
    public static DigitalInput shooterLimitSwitch2;
    public static DigitalInput shooterLimitSwitch1;
    public static DoubleSolenoid shooterDoubleSolenoid1;
    public static DoubleSolenoid shooterDoubleSolenoid2;
    public static DoubleSolenoid shooterDoubleSolenoid3;
    public static DigitalInput shooterDigitalInput1;
    public static DigitalInput shooterDigitalInput2;
    public static DigitalInput shooterDigitalInput3;
    public static DigitalInput shooterDigitalInput4;
    public static AnalogChannel shooterPotentiometer1;
    public static Compressor pneumaticsCompressor1;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        drivetrainSpeedController1 = new Victor(1, 3);
	LiveWindow.addActuator("Drivetrain", "Speed Controller 1", (Victor) drivetrainSpeedController1);
        
        drivetrainSpeedController2 = new Victor(1, 4);
	LiveWindow.addActuator("Drivetrain", "Speed Controller 2", (Victor) drivetrainSpeedController2);
        
        drivetrainRobotDrive2Motors = new RobotDrive(drivetrainSpeedController1, drivetrainSpeedController2);
	
        drivetrainRobotDrive2Motors.setSafetyEnabled(true);
        drivetrainRobotDrive2Motors.setExpiration(0.1);
        drivetrainRobotDrive2Motors.setSensitivity(0.5);
        drivetrainRobotDrive2Motors.setMaxOutput(1.0);
        
        drivetrainSpeedController3 = new Victor(1, 5);
	LiveWindow.addActuator("Drivetrain", "Speed Controller 3", (Victor) drivetrainSpeedController3);
        
        drivetrainSpeedController4 = new Victor(1, 6);
	LiveWindow.addActuator("Drivetrain", "Speed Controller 4", (Victor) drivetrainSpeedController4);
        
        drivetrainSpeedController5 = new Victor(1, 7);
	LiveWindow.addActuator("Drivetrain", "Speed Controller 5", (Victor) drivetrainSpeedController5);
        
        drivetrainSpeedController6 = new Victor(1, 8);
	LiveWindow.addActuator("Drivetrain", "Speed Controller 6", (Victor) drivetrainSpeedController6);
        
        drivetrainRobotDrive4Motors = new RobotDrive(drivetrainSpeedController3, drivetrainSpeedController4,
              drivetrainSpeedController5, drivetrainSpeedController6);
	
        drivetrainRobotDrive4Motors.setSafetyEnabled(true);
        drivetrainRobotDrive4Motors.setExpiration(0.1);
        drivetrainRobotDrive4Motors.setSensitivity(0.5);
        drivetrainRobotDrive4Motors.setMaxOutput(1.0);
        drivetrainQuadratureEncoder1 = new Encoder(1, 2, 1, 3, false, EncodingType.k4X);
	LiveWindow.addSensor("Drivetrain", "Quadrature Encoder 1", drivetrainQuadratureEncoder1);
        drivetrainQuadratureEncoder1.setDistancePerPulse(1.0);
        drivetrainQuadratureEncoder1.setPIDSourceParameter(PIDSourceParameter.kRate);
        drivetrainQuadratureEncoder1.start();
        drivetrainQuadratureEncoder2 = new Encoder(1, 4, 1, 5, false, EncodingType.k4X);
	LiveWindow.addSensor("Drivetrain", "Quadrature Encoder 2", drivetrainQuadratureEncoder2);
        drivetrainQuadratureEncoder2.setDistancePerPulse(1.0);
        drivetrainQuadratureEncoder2.setPIDSourceParameter(PIDSourceParameter.kRate);
        drivetrainQuadratureEncoder2.start();
        drivetrainUltrasonic1 = new Ultrasonic(1, 6, 1, 7);
	LiveWindow.addSensor("Drivetrain", "Ultrasonic 1", drivetrainUltrasonic1);
        
        collectorSpeedController1 = new Victor(1, 1);
	LiveWindow.addActuator("Collector", "Speed Controller 1", (Victor) collectorSpeedController1);
        
        collectorLimitSwitch1 = new DigitalInput(1, 14);
	LiveWindow.addSensor("Collector", "Limit Switch 1", collectorLimitSwitch1);
        
        collectorServo1 = new Servo(1, 2);
	LiveWindow.addActuator("Collector", "Servo 1", collectorServo1);
        
        shooterLimitSwitch2 = new DigitalInput(1, 13);
	LiveWindow.addSensor("Shooter", "Limit Switch 2", shooterLimitSwitch2);
        
        shooterLimitSwitch1 = new DigitalInput(1, 12);
	LiveWindow.addSensor("Shooter", "Limit Switch 1", shooterLimitSwitch1);
        
        shooterDoubleSolenoid1 = new DoubleSolenoid(1, 1, 2);      
	
        
        shooterDoubleSolenoid2 = new DoubleSolenoid(1, 3, 4);      
	
        
        shooterDoubleSolenoid3 = new DoubleSolenoid(1, 5, 6);      
	
        
        shooterDigitalInput1 = new DigitalInput(1, 8);
	LiveWindow.addSensor("Shooter", "Digital Input 1", shooterDigitalInput1);
        
        shooterDigitalInput2 = new DigitalInput(1, 9);
	LiveWindow.addSensor("Shooter", "Digital Input 2", shooterDigitalInput2);
        
        shooterDigitalInput3 = new DigitalInput(1, 10);
	LiveWindow.addSensor("Shooter", "Digital Input 3", shooterDigitalInput3);
        
        shooterDigitalInput4 = new DigitalInput(1, 11);
	LiveWindow.addSensor("Shooter", "Digital Input 4", shooterDigitalInput4);
        
        shooterPotentiometer1 = new AnalogChannel(1, 1);
	LiveWindow.addSensor("Shooter", "Potentiometer 1", shooterPotentiometer1);
        
        pneumaticsCompressor1 = new Compressor(1, 1, 1, 1);
	
        
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
