//Need to make this PID
package org.usfirst.frc190.CurrentRobotProject.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc190.CurrentRobotProject.Robot;
public class ArmDown extends Command {
    //May want to have this controlled via PID, instead of relying limit switches.
    private final double armDownSpeed = 1;
    public ArmDown() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    protected void initialize() {
        Robot.pivot.setElevatorMotor(-armDownSpeed);
    }
    protected void execute() {
    }
    protected boolean isFinished() {
        return Robot.pivot.lowerLimitSwitchPressed();
    }
    protected void end() {
        Robot.pivot.setElevatorMotor(0);
    }
    protected void interrupted() {
        end();
    }
}
