//This command needs work
package org.usfirst.frc190.CurrentRobotProject.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc190.CurrentRobotProject.Robot;
import org.usfirst.frc190.CurrentRobotProject.subsystems.Pivot;
import edu.wpi.first.wpilibj.InterruptableSensorBase;
/**
 *
 */
public class ArmLower extends Command {
    private double speed = 0.5;
    public ArmLower() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    
    protected void initialize() {
        
        if(Robot.oi.getAutomaticSwitch()){
            //Is automatic.
            this.cancel();
        }
        
        Robot.pivot.disable(); //Make sure that the PID loop is disabled.
        //The code below will end the command and stop the motor if one of the safety limit switches is hit.
        if(Robot.pivot.lowerLimitSwitchPressed() || Robot.pivot.topLimitSwitchPressed()){
            this.cancel();
            Robot.pivot.setElevatorMotor(0);
        }
        Robot.pivot.setElevatorMotor(-speed); //Turn of the pivot motor.
    }
    protected void execute() {
    }
    protected boolean isFinished() {
        //Will be controlled/finished by a button on the OI.
        return false;
    }
    protected void end() {
        Robot.pivot.setElevatorMotor(0);
    }
    protected void interrupted() {
        end();
    }
}
