//This command needs work
package org.usfirst.frc190.CurrentRobotProject.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc190.CurrentRobotProject.Robot;
import org.usfirst.frc190.CurrentRobotProject.subsystems.Pivot;
/**
 *
 */
public class ArmLower extends Command {
    private double speed = 0.5;
    public ArmLower() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    protected void initialize() {
        //TODO: disable PID before motor control.
        Robot.pivot.setElevatorMotor(-speed);
    }
    protected void execute() {
    }
    protected boolean isFinished() {
        //TODO: Add limit switch safeties.
        //Will be controlled/finished by a button on the OI.
        return false;
    }
    protected void end() {
        Robot.pivot.setElevatorMotor(0);
    }
    protected void interrupted() {
        end();
    }
}
