// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc190.CurrentRobotProject.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;


public class AutoManuver extends CommandGroup {
    
    private double collectTimeout = 3; //Change later if nessecary.
    
    public  AutoManuver() {
        addSequential(new DriveForward(10));
        addSequential(new DriveSpin(90, 0.5));
        addSequential(new Collect(collectTimeout));
        addSequential(new DriveSpin(-90, 0.5));
        addSequential(new DriveForward(-10));
    }
}
