//This command looks for the hot goal and waits until
//it's detected or timed out
package org.usfirst.frc190.CurrentRobotProject.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc190.CurrentRobotProject.Robot;
public class CheckForHotGoal extends Command {
    private double timeout = 5.5;
    public CheckForHotGoal() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    protected void initialize() {
        setTimeout(timeout);
    }
    protected void execute() {
    }
    protected boolean isFinished() {
        return isTimedOut() || Robot.shooter.goalIsHot();
    }
    protected void end() {
    }
    protected void interrupted() {
    }
}
