//
package org.usfirst.frc190.CurrentRobotProject.commands;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.Utility;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc190.CurrentRobotProject.Robot;
public class  DriveForwardSpeed extends Command {
    double timeout = 3;
    private final double tolerance = 0.01;
    private double maxSpeedLeft = 0.8;
    private double maxSpeedRight = 0.8;
    private double lastDist = 0;
    private double currDist = 50;
    private boolean checkDist = false;
    public DriveForwardSpeed() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.drivetrain);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    public DriveForwardSpeed(double speedleft, double speedright, double time, boolean check){
        requires(Robot.drivetrain);
        timeout = time;
        maxSpeedLeft = speedleft;
        maxSpeedRight = speedright;
        checkDist = check;
    }
    protected void initialize() {
        setTimeout(timeout);
    }
    protected void execute() {
        Robot.drivetrain.tankDrive(-maxSpeedLeft, -maxSpeedRight);
        lastDist = currDist;
        currDist = Robot.drivetrain.getEncoderDistanceRight();
        
    }
    protected boolean isFinished() {
        return isTimedOut() || ((Math.abs(currDist-lastDist) < tolerance)&&checkDist);
    }
    protected void end() {
        Robot.drivetrain.tankDrive(0, 0);
        System.out.println("end @ " + Utility.getFPGATime());
    }
    protected void interrupted() {
        end();
    }
}
