//

package org.usfirst.frc190.CurrentRobotProject.commands;
import edu.wpi.first.wpilibj.Utility;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc190.CurrentRobotProject.Robot;

public class  DriveForwardSpeed extends Command {
    double timeout = 3;
    private double maxSpeedLeft = 0.8;
    private double maxSpeedRight = 0.8;
    public DriveForwardSpeed() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.drivetrain);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    public DriveForwardSpeed(double speedleft, double speedright, double time){
        requires(Robot.drivetrain);
        timeout = time;
        maxSpeedLeft = speedleft;
        maxSpeedRight = speedright;
        
    }
    protected void initialize() {
        setTimeout(timeout);
        System.out.println("intitialize @ " + Utility.getFPGATime());
    }
    protected void execute() {
        Robot.drivetrain.tankDrive(-maxSpeedLeft, -maxSpeedRight);
    }
    protected boolean isFinished() {
        return isTimedOut();
    }
    protected void end() {
        Robot.drivetrain.tankDrive(0, 0);
        System.out.println("end @ " + Utility.getFPGATime());
    }
    protected void interrupted() {
        end();
    }
}
