//needs work
package org.usfirst.frc190.CurrentRobotProject.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc190.CurrentRobotProject.AutoDirection;
import org.usfirst.frc190.CurrentRobotProject.Robot;
import org.usfirst.frc190.CurrentRobotProject.ArduinoComm;
import org.usfirst.frc190.CurrentRobotProject.ArduinoMessages;
//This command makes the robot spin a set number of degrees at a specific speed.
public class  DriveSpin extends Command {
    
    private double turnSpeed = 0.5;
    private double spinAngle = 180;
    private double tolerance = 10;
    private double error;
    private double Kp = -1.0/90.0;
    
    public DriveSpin(double angle, double speed){
        turnSpeed = speed;
        spinAngle = angle;
        requires(Robot.drivetrain);
    }
    
    public DriveSpin() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.drivetrain);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    protected void initialize() {
        Robot.drivetrain.resetGyro();
    }
    
    protected void execute() {
        error = (spinAngle - Robot.drivetrain.getGyro());
        Robot.drivetrain.tankDrive(turnSpeed*Kp*error, -turnSpeed*Kp*error);
    }
    protected boolean isFinished() {
        return (Math.abs(error) <= tolerance);
    }
    
    protected void end() {
        Robot.drivetrain.stopDriveMotors();
    }
    protected void interrupted() {
        end();
    }
}
