//This command allows the joysticks to drive the robot.
//It is always running except when interruted.
//This command also sets an on-board indicator based on the ultrasonic sensor.
package org.usfirst.frc190.CurrentRobotProject.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc190.CurrentRobotProject.Robot;
public class DriveWithJoysticks extends Command {
    public DriveWithJoysticks() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.drivetrain);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    protected void initialize() {
    }
    protected void execute() {
        //This slows the robot down for demos
        //Full speed is turned on when the manual switch is flipped up
        if(!Robot.oi.manualSwitch.get()){
            Robot.drivetrain.tankDrive(Robot.oi.leftJoystick, Robot.oi.rightJoystick, 1);
        } else {
            Robot.drivetrain.tankDrive(Robot.oi.leftJoystick, Robot.oi.rightJoystick, 1);
        }
        
    }
    protected boolean isFinished() {
        return false;
    }
    protected void end() {
        Robot.drivetrain.stopDriveMotors();
    }
    protected void interrupted() {
        end();
    }
}
