//This command extends piston three to unlatch and fire the shooter
package org.usfirst.frc190.CurrentRobotProject.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc190.CurrentRobotProject.Robot;

public class ExtendLatch extends Command {

    private boolean isManual;

    public ExtendLatch() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.shooter);
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        //isManual = Robot.oi.manualSwitch.get();
        isManual = true;
    }

    public ExtendLatch(boolean run) {
        requires(Robot.collector);
        isManual = run;
    }

    protected void initialize() {
        if (isManual) {
            Robot.shooter.extendLatchPiston();
        }
    }

    protected void execute() {
    }

    protected boolean isFinished() {
        return true;
    }

    protected void end() {
    }

    protected void interrupted() {
        end();
    }
}
