//This command extends Piston 2
package org.usfirst.frc190.CurrentRobotProject.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc190.CurrentRobotProject.Robot;
public class  ExtendPiston2 extends Command {
    public ExtendPiston2() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.shooter);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    protected void initialize() {
        Robot.shooter.extend2();
    }
    protected void execute() {
    }
    protected boolean isFinished() {
         return true;
    }
    protected void end() {
    }
    protected void interrupted() {
        end();
    }
}
