//
package org.usfirst.frc190.CurrentRobotProject.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc190.CurrentRobotProject.Robot;
import org.usfirst.frc190.CurrentRobotProject.RobotMap;
public class  LimitDriveSpeed extends Command {
    
    double maxSpeed;
    
    public LimitDriveSpeed() {
        this(0.5);
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    public LimitDriveSpeed(double speed){
        maxSpeed = speed;
    }
    protected void initialize() {
        Robot.drivetrain.setMaxSpeed(maxSpeed);
    }
    protected void execute() {
    }
    protected boolean isFinished() {
        return true;
    }
    protected void end() {
    }
    protected void interrupted() {
        end();
    }
}
