//This is the Move arm command
//It move the arm to a specified setpoint (default setpoint is 1.0)
package org.usfirst.frc190.CurrentRobotProject.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc190.CurrentRobotProject.Robot;
public class MoveArmToPoint extends Command {
    private double setPoint = 1.0;
    private boolean setPointSetInCode = false;
    
    public MoveArmToPoint() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.pivot);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        setPointSetInCode = false;
    }
    
    public MoveArmToPoint(double armSetpoint) {
        requires(Robot.pivot);
        setPoint = armSetpoint;
        setPointSetInCode = true;
    }
    
    protected void initialize() {
        Robot.pivot.enable();
        Robot.pivot.setSetpoint(setPoint);
    }
    
    protected void execute() {
    }
    
    protected boolean isFinished() {
        if (Robot.pivot.lowerLimitSwitchPressed() || Robot.pivot.topLimitSwitchPressed()) {
            return true; //Stop the command if one of the limit switches is hit.
        }
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ISFINISHED
        return Robot.pivot.onTarget();
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ISFINISHED
    }
    
    protected void end() {
        Robot.pivot.disable();
        Robot.pivot.setElevatorMotor(0);
    }
    
    protected void interrupted() {
        end();
    }
}
