//This command opens the claw
package org.usfirst.frc190.CurrentRobotProject.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc190.CurrentRobotProject.Robot;
import org.usfirst.frc190.CurrentRobotProject.ArduinoMessages;
public class OpenClaw extends Command {
    private boolean isManual;
    public OpenClaw() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.collector);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        isManual = false;
    }
    public OpenClaw(boolean run){
        requires(Robot.collector);
        isManual = true;
    }
    protected void initialize() {
        if(Robot.oi.manualSwitch.get()||!isManual){
        Robot.I2CComm.sendMessage(ArduinoMessages.OPENING_CLAW);
        Robot.collector.openClaw();}
    }
    
    protected void execute() {
    }
    
    protected boolean isFinished() {
        return true;
    }
    
    protected void end() {
    }
    
    protected void interrupted() {
        end();
    }
}
