//This command raises the pivot until the button is released or it hits 
//the upper limit switch
package org.usfirst.frc190.CurrentRobotProject.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc190.CurrentRobotProject.Robot;
import org.usfirst.frc190.CurrentRobotProject.ArduinoMessages;
public class PivotRaise extends Command {
    public boolean isManual;
    double motorSpeed = 0.8;
    
    public PivotRaise() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        isManual = false;
    }
    
    public PivotRaise(boolean run) {
        isManual = true;
    }
    protected void initialize() {
        if(Robot.oi.manualSwitch.get()||!isManual){
        Robot.I2CComm.sendMessage(ArduinoMessages.RAISING_PIVOT);
        Robot.pivot.disable();
        Robot.collector.setRollerSpeed(0);
        }
    }
    protected void execute() {
        if(Robot.oi.manualSwitch.get()||!isManual){
        Robot.pivot.setMotor(motorSpeed);
        }
    }
    protected boolean isFinished() {
        return Robot.pivot.topLimitSwitchPressed();
    }
    protected void end() {
        Robot.pivot.setMotor(0);
    }
    protected void interrupted() {
        end();
    }
}
