//
package org.usfirst.frc190.CurrentRobotProject.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc190.CurrentRobotProject.Robot;
public class  PivotLowGoal extends Command {
    public PivotLowGoal() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.pivot);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    protected void initialize() {
        Robot.pivot.disable();
        while(Robot.pivot.lowerLimitSwitchPressed()){
            System.out.println("Lower Limit");
            Robot.pivot.setMotor(0.5);
        }while(Robot.pivot.topLimitSwitchPressed()){
            Robot.pivot.setMotor(-0.5);
        }
        System.out.println("Low Goal Position Init");
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INITIALIZE
        Robot.pivot.enable();
        Robot.pivot.setSetpoint(1.0);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INITIALIZE
        Robot.pivot.setSetpoint(Robot.pivot.getLowGoalValue());
    }
    protected void execute() {
    }
    protected boolean isFinished() {
        return (Robot.pivot.onTarget()||Robot.pivot.lowerLimitSwitchPressed()||Robot.pivot.topLimitSwitchPressed());
    }
    protected void end() {
        if(Robot.pivot.lowerLimitSwitchPressed()||Robot.pivot.topLimitSwitchPressed()) {
            Robot.pivot.disable();
        }
        System.out.println("Low Goal in Position");
    }
    protected void interrupted() {
        Robot.pivot.disable();
    }
}
