//This command lowers the pivot until the button is released or the lower
//limitswitch is released
package org.usfirst.frc190.CurrentRobotProject.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc190.CurrentRobotProject.Robot;
import org.usfirst.frc190.CurrentRobotProject.ArduinoMessages;
public class  PivotLower extends Command {
    public boolean isManual;
    double motorSpeed = 0.8;
    
    public PivotLower() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        isManual = false;
    }
    public PivotLower(boolean run){
        isManual = true;
    }
    
    public PivotLower(double time){
        setTimeout(time);
    }
    
    protected void initialize() {
        if(Robot.oi.manualSwitch.get()||!isManual){
        Robot.I2CComm.sendMessage(ArduinoMessages.LOWERING_PIVOT);
        Robot.pivot.disable();
        }
    }
    protected void execute() {
        if(Robot.oi.manualSwitch.get()||!isManual){
        Robot.pivot.setMotor(-motorSpeed);
        }
    }
    protected boolean isFinished() {
        return Robot.pivot.lowerLimitSwitchPressed()||isTimedOut();
    }
    protected void end() {
        Robot.pivot.setMotor(0);
    }
    protected void interrupted() {
        end();
    }
}
