//This command sets the setpoint to the far shotting position and moves the
//pivot to that position
package org.usfirst.frc190.CurrentRobotProject.commands;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.WaitCommand;
import org.usfirst.frc190.CurrentRobotProject.Robot;
public class  PivotFarPosition extends Command {
    
    private double degrees = 50;
    
    public PivotFarPosition() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.pivot);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    protected void initialize() {
        Robot.pivot.disable();
        while(Robot.pivot.lowerLimitSwitchPressed()){
            System.out.println("Lower Limit");
            Robot.pivot.setMotor(0.5);
        }while(Robot.pivot.topLimitSwitchPressed()){
            Robot.pivot.setMotor(-0.5);
        }
        System.out.println("Shoot Far Init");
        
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INITIALIZE
        Robot.pivot.enable();
        Robot.pivot.setSetpoint(1.0);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INITIALIZE
        //Robot.pivot.setSetpoint(Robot.pivot.degreesToPotValue2(degrees));
        //Robot.pivot.setSetpoint(2.350);  //Auto short value = 2.350
        Robot.pivot.setSetpoint(Robot.pivot.getFarValue());  //Auto long value = 2.350
    }
    protected void execute() {
    }
    protected boolean isFinished() {
        return (Robot.pivot.onTarget()||Robot.pivot.lowerLimitSwitchPressed()||
                    Robot.pivot.topLimitSwitchPressed()||Robot.oi.boomButton.get());
    }
    protected void end() {
        if(Robot.pivot.lowerLimitSwitchPressed()||Robot.pivot.topLimitSwitchPressed()) {
            Robot.pivot.disable();
        }
        System.out.println("Shoot Far End");
    }
    protected void interrupted() {
        Robot.pivot.disable();
    }
}
