//
package org.usfirst.frc190.CurrentRobotProject.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc190.CurrentRobotProject.Robot;
public class  RollersInThenStop extends Command {
    private double timeout = 0;
    public RollersInThenStop() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.collector);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    
    public RollersInThenStop(double time) {
        timeout = time;
    }
    protected void initialize() {
        setTimeout(timeout);
        Robot.collector.setRollerSpeed(-1);
    }
    protected void execute() {
    }
    protected boolean isFinished() {
        return Robot.collector.isCollected() || isTimedOut();
    }
    protected void end() {
        Robot.collector.setRollerSpeed(0);
    }
    protected void interrupted() {
        end();
    }
}
