//
package org.usfirst.frc190.CurrentRobotProject.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc190.CurrentRobotProject.Robot;
public class  RollersInThenStop extends Command {
    public RollersInThenStop() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.collector);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    
    public RollersInThenStop(double time) {
        setTimeout(time);
    }
    protected void initialize() {
        if(!Robot.collector.isCollected()){
            Robot.collector.setRollerSpeed(-1);
        }
    }
    protected void execute() {
        if(!Robot.collector.isCollected()){
            Robot.collector.setRollerSpeed(-1);
        } else {
            Robot.collector.setRollerSpeed(0);
        }
    }
    protected boolean isFinished() {
        return Robot.collector.isCollected() || isTimedOut();
    }
    protected void end() {
        Robot.collector.setRollerSpeed(0);
    }
    protected void interrupted() {
        end();
    }
}
