// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc190.CurrentRobotProject.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;
import edu.wpi.first.wpilibj.command.WaitCommand;

/**
 *
 */
public class ShootFar extends CommandGroup {
    
    public  ShootFar() {
        //None of the sequences for the pneumatics system need addParallel.
        //The commands take so little time there is no need.
        
        addSequential(new RetractPiston1());
        addSequential(new DepressurizePiston2());
        addSequential(new WaitCommand(.3));
        addSequential(new ExtendPiston1());
        addSequential(new WaitCommand(.2));
        addSequential(new PressurizePiston2());
        //TODO: Aim arm.
    }
}
