// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc190.CurrentRobotProject.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;
import edu.wpi.first.wpilibj.command.WaitCommand;
import org.usfirst.frc190.CurrentRobotProject.AutoDirection;
import org.usfirst.frc190.CurrentRobotProject.Robot;

/**
 *
 */
public class TwoBallAuto extends CommandGroup {
    
    private double collectionTimeout = 2; //Needs to be tested.
     
    public  TwoBallAuto() {
        switch(Robot.getAutonomousDirection().value){
            case 0:
                //LEFT
                break;
            case 1:
                //RIGHT
                break;
            case 2:
                //FORWARD
                break;
            case 3:
                //NO MOVEMENT
                break;
                
        }
        
        
        addSequential(new ShootFar());
        //Wait for Hot Goal.
        addSequential(new Fire());
        addSequential(new Collect(collectionTimeout));
        
        
        /*
        addSequential(new DepressurizePiston2());
        addSequential(new WaitCommand(.3));
        addSequential(new ExtendPiston1());
        addSequential(new WaitCommand(.2));
        addSequential(new PressurizePiston2());
        addSequential(new WaitCommand(.5));
        addSequential(new Fire());
        //addSequential(new Collect());
        addSequential(new WaitCommand(0.5));
        
        addSequential(new OneBallAuto());
        addSequential(new WaitCommand(0.5));
        */
        
    }
}
