//This command turns on the collector motors
//If a value is passed in for the time the collector
//will stop when its hit with the limitswitch or the timeout stops
//Otherwise the motors stay on forward until the command is interrupted
package org.usfirst.frc190.CurrentRobotProject.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc190.CurrentRobotProject.Robot;
public class WaitForCollection extends Command {

    
    public WaitForCollection(double collectionTimeout) {
        setTimeout(collectionTimeout);
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.collector);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    
    public WaitForCollection() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.collector);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    
    protected void initialize() {
    }
    
    protected void execute() {
    }
    
    protected boolean isFinished() {
        return (Robot.collector.isCollected() || isTimedOut());
        //Wait for the ball to hit the limit switch 
        //or for the command to timeout.
    }
    
    protected void end() {
    }
    
    protected void interrupted() {
        end();
    }
}
