//
package org.usfirst.frc190.CurrentRobotProject.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc190.CurrentRobotProject.Robot;
public class  WaitToFire extends Command {
    private boolean checkForBall = true;
    public WaitToFire() {
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    public WaitToFire(boolean check) {
	checkForBall = check;
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    protected void initialize() {
    }
    protected void execute() {
    }
    protected boolean isFinished() {
        return (((Robot.collector.isClawOpen() && Robot.collector.isCollected()) || Robot.oi.boomButton.get())&&checkForBall)
                ||(Robot.collector.isClawOpen()&&(!checkForBall));
    }
    protected void end() {
    }
    protected void interrupted() {
    }
}
